### PR TITLE
Change background of FAQ & anchor color

### LINKED ISSUE #37: FAQ Content

### LINKED ISSUE #48: [FAQ Section] Change BG to pastel version and make Q&A more distinct
- Change the background of the section to a more pastel green and the text to a more dark color (but not black). See image for reference above but don't take colors too seriously (I personally think it could be a lighter green).
- Make the Questions more distinct than the answers. I think the switch to the pastel colors will already do most of this for you but play around with borders, underlines, colors, or all of the above to make the Qs more distinct.
- Make links have an underline of sorts (for clarity). The links in the screenshot above are a `wavy` underline

In general, this is a pretty open-ended issue, please send many screenshots of possible versions in this issue.

### PR DESCRIPTION
**Pull request by samarthdave**
Closes #48 
Update: Closes #37 too 😄

### CODE REVIEW

**Comment by samarthdave** [comment]
Uh oh... I tried to do too much and templatize the FAQ section. Can you help with the linting? I'll try and get the colors right in the meantime.

**Comment by geooot** [comment]
No worries you just have to click details and resolve, and the listing tool will automatically create a PR that fixes the issues.

**Comment by samarthdave** [comment]
Okay so the answers take a lot of space. Should we reconsider our choice to not use dropdowns?

**Comment by geooot** [comment]
Nah, for now, its okay. Merging

**Pull request merged**
