### PR TITLE
Add day of schedule

### PR DESCRIPTION
**Pull request by danielabreo**
Screen Shot 2020-10-10 at 9 29 02 PM

### CODE REVIEW

**Comment by phulsechinmay** [comment]
@danielabreo Can we get some custom CSS here? Like coloring workshops and more?

**Comment by geooot** [comment]
@danielabreo Also is the first column really needed?

**Comment by phulsechinmay** [comment]
@geooot @danielabreo If we color-coded them in some way, we could get rid of the first column and keep the information it provides

**Comment by danielabreo** [comment]
@geooot 
Screen Shot 2020-10-13 at 10 51 50 AM

**Pull request merged**
