### PR TITLE
team page updates

### PR DESCRIPTION
**Pull request by gcpetri**

### CODE REVIEW

**Comment by gcpetri** [comment]
shows an error in team.ejs but its actually working just a linting thing idk how to fix yet

**Comment by geooot** [comment]
very cool kanye. i do think that animation speed could be higher.

also that unibeautify error isnt really that important honestly

**Comment by gcpetri** [comment]
> very cool kanye. i do think that animation speed could be higher.
> 
> also that unibeautify error isnt really that important honestly

the timing was so hard to get down lol but i can try speeding it up

**Comment by gcpetri** [comment]
how's that? @geooot

**Comment by geooot** [comment]
I was thinking around 0.5s like so.

https://user-images.githubusercontent.com/7832610/169917574-3157366c-e2de-45ff-8b1f-fd137330c86d.mov

Also some elements have a bottom set to 300px when they are much shorter so I adjusted those. (in inspect element ofc, i cant code)

**Pull request merged**
