### PR TITLE
Change apply and register buttons to use CSS transitions and be subtler

### PR DESCRIPTION
**Pull request by geooot**
- Change buttons to use transition instead of CSS animation
- Make the buttons more subtle on hover animation
- Swap button colors

### CODE REVIEW

**Comment by phulsechinmay** [comment]
The size of the buttons weirdly looks different for some reason. Also, should we make both of them only-bordered for consistency?

**Comment by geooot** [comment]
@phulsechinmay 
The idea is to have one be a primary one, and one be secondary. Here are some other options.
Other options:
1. Both buttons outlined:
image

2. Both buttons filled:
image

**Comment by phulsechinmay** [comment]
I think both being outline looks pretty good, just increased the outline to 2px for more emphasis. 
We could use a scheme like such:
* Outlined button for items that take you to separate pages or scroll on the same page
* Filled buttons for items that take you to forms / limited period stuff

But that might be over-engineering the buttons, so either is fine tbh

**Comment by geooot** [comment]
This is kinda wacky lol, but what do you think about this: 
image

**Pull request merged**
